version: '3'

services:
  app-db:
    build: 
      context: ./app-db/
    image: momedesjunior/fullcycle-course-docker-app-db
    container_name: app-db
    restart: always
    tty: true
    volumes:
      - ./app-db/app-db-data:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: ./app/
    image: momedesjunior/fullcycle-course-docker-app
    container_name: app
    entrypoint: dockerize -wait tcp://app-db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    networks:
      - app-network
    tty: true
    depends_on:
      - app-db
  
  nginx:
    build:
      context: ./nginx
    image: momedesjunior/fullcycle-course-docker-nginx
    container_name: nginx
    entrypoint: dockerize -wait tcp://app-db:3306 -timeout 20s /docker-entrypoint.sh
    command: "nginx -g 'daemon off;'"
    networks:
      - app-network
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - app


networks:
  app-network:
    driver: bridge